version: '3.8'

services:
  mlflow:
    image: python:3.10-slim
    working_dir: /mlflow
    volumes:
      - ./mlflow.db:/mlflow/mlflow.db           # Mount SQLite DB file
      - ./mlruns:/mlflow/mlruns                 # Mount artifact root
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install mlflow &&
             mlflow server 
             --backend-store-uri sqlite:///mlflow.db 
             --default-artifact-root ./mlruns 
             --host 0.0.0.0 
             --port 5000"
  
  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mlflow
