
data_ingestion:
  data_ingestion_directory: artifacts/data_ingestion_directory
  raw_data_folder: artifacts/data_ingestion_directory/raw_data
  raw_data_file: artifacts/data_ingestion_directory/raw_data/raw_data.csv
  split_data_folder: artifacts/data_ingestion_directory/ingested_data
  train_filepath: artifacts/data_ingestion_directory/ingested_data/train.csv
  test_filepath: artifacts/data_ingestion_directory/ingested_data/test.csv
  database_name: Network_Security
  collection_name: Websites

data_validation:
  data_validation_directory: artifacts/data_validation_directory
  valid_data_directory: artifacts/data_validation_directory/valid_data_directory
  invalid_data_directory: artifacts/data_validation_directory/invalid_data_directory
  valid_train_data_filepath: artifacts/data_validation_directory/valid_data_directory/valid_train_data.csv
  valid_test_data_filepath: artifacts/data_validation_directory/valid_data_directory/valid_test_data.csv
  invalid_train_data_filepath: artifacts/data_validation_directory/valid_data_directory/invalid_train_data.csv
  invalid_test_data_filepath: artifacts/data_validation_directory/valid_data_directory/invalid_test_data.csv
  drift_report_filepath: artifacts/data_validation_directory/drift_report.yaml
  schema_filepath: artifacts/schema/schema.yaml

data_transformation:
  data_transforamtion_directory: artifacts/data_transforamtion_directory
  model_directory: artifacts/model_directory
  knn_imputer_model_filepath: artifacts/model_directory/knn_imputer_model.pkl
  feature_selection_model_filepath: artifacts/model_directory/feature_selection_model.pkl
  transformed_train_data_filepath: artifacts/data_transforamtion_directory/transformed_train_data.csv
  transformed_test_data_filepath: artifacts/data_transforamtion_directory/transformed_test_data.csv

model_training:
  model_training_directory: artifacts/model_training_directory
  best_model_filepath: artifacts/model_directory/best_model.pkl
  model_metrics_filepath: artifacts/model_training_directory/metrics.yaml
  

  
